x-image:
  &image
  build: .
  image: exign:0.8.0

version: "3.0"
services:
  exign:
    <<: *image
    restart: unless-stopped
    environment:
      EXIGN_CLIENT_BODY_BUFFER_SIZE:
      EXIGN_UPSTREAMS_DOUBLEDASH_DOMAINS:
      EXIGN_UPSTREAMS_HOSTMAP:
      EXIGN_UPSTREAMS_SECURE:
      EXIGN_SIGNATURE_KEYFILE:
      EXIGN_SIGNATURE_PUBKEYFILE:
      EXIGN_TRANSPORT_CA_KEYFILE:
      EXIGN_TRANSPORT_CA_CERTFILE:
      EXIGN_REMOTE_CONFIG_URL:
      EXIGN_REMOTE_CONFIG_DIRECTORY:
      EXIGN_DNS_RESOLVER: 127.0.0.11 # use docker internal server

      NODE_EXTRA_CA_CERTS: /src/config/backend-transport/ca.crt
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    ports:
      - 53:53/udp
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "3000:3000"
    volumes:
      - ./config:/src/config
    healthcheck: 
      test: [CMD, curl, -s, "localhost:3000/index.html"]
      start_period: 10s
      interval: 3s
      retries: 100

  connection-test:
    <<: *image
    restart: on-failure
    depends_on:
      exign:
        condition: service_healthy
    environment:
      SOCKS5_PROXY_ENDPOINT: exign:1080
      EXIGN_HOSTNAME: exign
    volumes:
      - ./config:/src/config
    entrypoint: [ bash, -c ]
    command:
      - ./scripts/append-hosts.sh && ./scripts/connection-test.sh && ./scripts/commit-config.sh
