x-image:
  &image
  build: .
  image: exign:0.12.3

version: "3.0"
services:
  exign:
    <<: *image
    restart: unless-stopped
    environment:
      EXIGN_DIGEST_MEMORY_BUFFER_SIZE:
      EXIGN_DIGEST_FILE_BUFFER_POOL_MIN:
      EXIGN_DIGEST_FILE_BUFFER_POOL_MAX:
      EXIGN_UPSTREAMS_DOUBLEDASH_DOMAINS:
      EXIGN_UPSTREAMS_HOSTMAP:
      EXIGN_UPSTREAMS_SECURE:
      EXIGN_CONFIG_DIRECTORY:
      EXIGN_REMOTE_CONFIG_URL:
      EXIGN_DNS_RESOLVER: ${EXIGN_DNS_RESOLVER:-127.0.0.11} # default use docker compose dns server

      NODE_EXTRA_CA_CERTS: /src/config/upstream-transport/ca.crt
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    ports:
      - 53:53/udp
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config:/src/config
      - ./logs:/src/logs
    healthcheck:
      test: [ CMD, curl, -s, "localhost:3000/index.html" ]
      start_period: 10s
      interval: 3s
      retries: 100
