version: "3.9"
services:
  frproxy:
    build: .
    restart: unless-stopped
    depends_on:
      keygen:
        condition: service_completed_successfully
    environment:
      FRPROXY_CLIENT_BODY_BUFFER_SIZE:
      FRPROXY_DOUBLEDASH_PARENT_DOMAINS:
      FRPROXY_SIGNATURE_KEYFILE:
      FRPROXY_SIGNATURE_PUBKEYFILE:
      FRPROXY_TRANSPORT_CA_KEYFILE:
      FRPROXY_TRANSPORT_CA_CERTFILE:
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./keys:/usr/src/app/keys

  keygen:
    image: node:18
    restart: on-failure
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: []
    command: ./keygen.sh
