x-image:
  &image
  build: .
  image: httpsig-frproxy:0.7.0

x-script:
  &script
  <<: *image
  restart: on-failure
  volumes:
    - ./config:/src/config

x-dnsmasq:
  &dnsmasq
  <<: *image
  restart: unless-stopped
  volumes:
    - ./config:/src/config
  entrypoint:
    - dnsmasq
    - -k
    - --log-facility=-
    - --no-host
    - --no-resolv
    - --addn-hosts=/src/config/hosts

version: "3.9"
services:
  init:
    <<: *script
    entrypoint: [ bash, -c ]
    environment:
      REMOTE_CONFIG_URL:
      REMOTE_CONFIG_USE_FRPROXY:
    command:
      - ./scripts/keygen.sh && ./scripts/remote-config.sh && ./scripts/commit-config.sh

  frproxy:
    <<: *image
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      FRPROXY_CLIENT_BODY_BUFFER_SIZE:
      FRPROXY_DOUBLEDASH_DOMAINS:
      FRPROXY_SIGNATURE_KEYFILE:
      FRPROXY_SIGNATURE_PUBKEYFILE:
      FRPROXY_TRANSPORT_CA_KEYFILE:
      FRPROXY_TRANSPORT_CA_CERTFILE:
      FRPROXY_PROXY_SECURE:
      FRPROXY_HOSTMAP:

      DOTENV_CONFIG_PATH: /src/config/.env
      NODE_EXTRA_CA_CERTS: /src/config/backend-transport/ca.crt
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./config:/src/config

  dnsmasq:
    <<: *image
    depends_on:
      init:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "53:53"
      - 53:53/udp
    volumes:
      - ./config:/src/config
    entrypoint:
      - dnsmasq
      - -k
      - --log-facility=-
      - --no-host
      - --no-resolv
      - --addn-hosts=/src/config/hosts
    command:
      - --server=8.8.8.8
      - --server=8.8.4.4
      - --server=1.1.1.1

  socks5:
    <<: *image
    restart: unless-stopped
    depends_on:
      - frproxy
    environment:
      PROXY_PORT: 1080
    ports:
      - 1080:1080
    volumes:
      - ./config:/src/config
    entrypoint: [ ./scripts/append-hosts.sh, socks5 ]

  connection-test:
    <<: *script
    depends_on: [ frproxy ]
    network_mode: service:socks5
    environment:
      SOCKS5_PROXY_ENDPOINT: socks5:1080
    entrypoint: [ ./scripts/connection-test.sh ]
